# Generated by Django 5.2.5 on 2026-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('disease', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('solution', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True))
            ],
        ),
    ]
